name: 'ðŸ³ Build docker image'

on: push

env:
  CLEAN_BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  build:
    name: ðŸ—ï¸ Build
    runs-on: ubuntu-latest

    steps:
      - name: Add clean branch name in env
        # First sed is to get branch name, second is to replace "/" with "-" in branch names
        run: echo "BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,' | sed -e 's/\//-/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        #continue-on-error: true

      - name: Build the Docker image
        run: docker build . --file docker/web/Dockerfile --tag mec-$BRANCH:latest
