name: 'ðŸ³ Build docker image'

on: push

env:
  CLEAN_BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  build:
    name: ðŸ—ï¸ Build
    runs-on: ubuntu-latest

    steps:
      - name: Add clean branch name in env
        # First sed is to get branch name, second is to replace "/" with "-" in branch names
        run: echo "BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,' | sed -e 's/\//-/g')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3

      - name: Manage docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        #continue-on-error: true

      - name: Build Docker image
        run: docker build . --file docker/web/Dockerfile --tag mec-$BRANCH:latest

      - name: Login to registry
        run: docker login rg.fr-par.scw.cloud/mon-espace-collectivite -u nologin --password-stdin <<< "$SCW_SECRET_KEY"

      - name: Tag image
        run: docker tag mec-$BRANCH:latest rg.fr-par.scw.cloud/mon-espace-collectivite/mec-$BRANCH:latest

      - name: Push to registry
        run: docker push rg.fr-par.scw.cloud/mon-espace-collectivite/mec-$BRANCH:latest
