name: 'ğŸ³ Build docker image'

on: push

env:
  CLEAN_BRANCH_NAME: ${BRANCH_NAME//\//-}

jobs:
  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest

    steps:
      - run: echo $CLEAN_BRANCH_NAME
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        #continue-on-error: true

      - name: Build the Docker image
        run: docker build . --file docker/web/Dockerfile --tag mec-$CLEAN_BRANCH_NAME:$(date +%s)
